feat: fix taskfiles

diff --git a/DevEx/taskfile/Taskfile.terratest.yml b/DevEx/taskfile/Taskfile.terratest.yml
--- a/DevEx/taskfile/Taskfile.terratest.yml
+++ b/DevEx/taskfile/Taskfile.terratest.yml
@@ -2,21 +2,20 @@
 version: '3'
 
 vars:
-    working_dir: '{{default "." .working_dir}}'
-
+    SRC_DIR: '{{default "." .SRC_DIR}}'
+    TEST_NAME_PREFIX: '{{default "Test" .TEST_NAME_PREFIX}}'
+    TEST_TYPE: '{{default "unit" .TEST_TYPE}}'
 
 tasks:
     clean:
         desc: Clean all the .terraform cache, and golang cache or binaries compiled if applicable.
-        dir: '{{.working_dir}}'
         cmds:
             - |
-              echo "Current working directory path: $(pwd)"
-              echo "working_dir_unit: {{.working_dir}}"
-              echo "----------------------------------"
-              echo
+              echo "Working directory passed: {{.SRC_DIR}}"
+              echo "Full path: $(pwd)/{{.SRC_DIR}}"
+              echo ""
 
-              ls -ltrah
+              cd {{.SRC_DIR}}
 
               if [ -f "go.mod" ]; then
                 go clean -cache -testcache -modcache -i -r
@@ -26,57 +25,125 @@ tasks:
                 rm -rf .terraform
               fi
 
+              echo "[ ok ] Cleaned all the cache"
+              echo "------------------------------------------------------------"
+        silent: true
+
     is-valid-terratest:
         desc: Check if the terratest folder is valid
-        dir: '{{.working_dir}}'
         cmds:
             - |
-              echo "Current working directory path: $(pwd)"
-              echo "working_dir_unit: {{.working_dir}}"
-              echo "----------------------------------"
-              echo
-              TEST_FILES=$(find . -name "*_test.go")
+              echo "Working directory passed: {{.SRC_DIR}}"
+              echo "Full path: $(pwd)/{{.SRC_DIR}}"
+              echo ""
 
-              # If there are Go test files, run the tests
-              if [ -n "$TEST_FILES" ]; then
-                echo "Terratest folder is valid"
-              else
-                echo "Terratest folder is not valid"
+              echo "       _______"
+              echo "      /       \\"
+              echo "      |   0   |"
+              echo "      |   _   |"
+              echo "      \_______/"
+              echo "Running terratest pre-checks"
+              echo "============================================================"
+
+              src_dir=$(dirname {{.SRC_DIR}})
+              module=$(basename $src_dir)
+              recipe={{.TEST_NAME_PREFIX}}
+              testType={{.TEST_TYPE}}
+              testName="Test${module^}${recipe^}${testType^}"
+              testDirResolved="$module/$testType"
+
+              if [ ! -f "{{.SRC_DIR}}/go.mod" ]; then
+                echo "[ x ] go.mod file not found in {{.SRC_DIR}}"
                 exit 1
               fi
 
-    run-all-nocache:
-        desc: Run all the Go tests in this directory, without cache.
-        dir: '{{.working_dir}}'
-        cmds:
-            - |
-              echo "Current working directory path: $(pwd)"
-              echo "working_dir_unit: {{.working_dir}}"
-              echo "----------------------------------"
-              echo
+              echo "[ ! ] Test src dir: $src_dir"
+              echo "-----------------------------------------"
+              echo "[ ! ] Test module: $module"
+              echo "-----------------------------------------"
+              echo "[ ! ] Test recipe: $recipe"
+              echo "-----------------------------------------"
+              echo "[ ! ] Test directory selected: $testDirResolved"
+              echo "-----------------------------------------"
+              echo ""
 
-              TEST_FILES=$(find . -name "*_test.go")
+              if [ "$testType" != "integration" ] && [ "$testType" != "unit" ]; then
+                echo "[ x ] Invalid test type. Must be either integration or unit"
+                exit 1
+              fi
 
-              if [ -n "$TEST_FILES" ]; then
-                  go test -v -count=1 -timeout 30m -parallel 128 -run . $TEST_FILES
-              else
-                  echo "No Go test found, perhaps you should run task is-valid-terratest first?"
+              if [[ $testName != Test* ]]; then
+                  echo "[ x ] Invalid test name. Must start with the word Test"
                   exit 1
               fi
 
+              if [ ! -d "$testDirResolved" ]; then
+                  echo "[ x ] Invalid test directory. Could not find $testDirResolved"
+                  exit 1
+              fi
+
+              cd $testDirResolved
+
+              TEST_FILES=$(find . -name "*_test.go")
+
+              echo "[ ! ] Test files found: $TEST_FILES"
+
+              if [! -n "$TEST_FILES" ]; then
+                  echo "[ x ] Could not find any Go test files in $SRC_DIR"
+                  exit 1
+              fi
+
+              echo "[ ok ] All pre-checks passed"
+        silent: true
+
+
+    run-all-nocache:
+        desc: Run all the Go tests in this directory, without cache.
+        cmds:
+            - |
+              echo "       _______"
+              echo "      /       \\"
+              echo "      |   0   |"
+              echo "      |   _   |"
+              echo "      \_______/"
+              echo "Running Tests without cache"
+              echo "============================================================"
+
+              src_dir=$(dirname {{.SRC_DIR}})
+              module=$(basename $src_dir)
+              recipe={{.TEST_NAME_PREFIX}}
+              testType={{.TEST_TYPE}}
+              testName="Test${module^}${recipe^}${testType^}"
+              testDirResolved="$module/$testType"
+
+              cd $testDirResolved
+              go test -v -count=1 -timeout 30m -parallel 128 -run "^$testName"
+
+              echo "[ ok ] Finished running terratest tests"
+        silent: true
+
     run-all-cache:
-        dir: '{{.working_dir}}'
         desc: Run all the Go tests in this directory, with cache.
         cmds:
             - |
-              echo "Current working directory path: $(pwd)"
-              echo "working_dir_unit: {{.working_dir}}"
-              echo "----------------------------------"
-              echo
-              TEST_FILES=$(find . -name "*_test.go")
-              if [ -n "$TEST_FILES" ]; then
-                go test -v -timeout 30m -parallel 128 -run . $TEST_FILES
-              else
-                echo "No Go test found, perhaps you should run task is-valid-terratest first?"
-                exit 1
-              fi
+              echo "       _______"
+              echo "      /       \\"
+              echo "      |   0   |"
+              echo "      |   _   |"
+              echo "      \_______/"
+              echo "Running Test with cache"
+              echo "============================================================"
+
+              src_dir=$(dirname {{.SRC_DIR}})
+              module=$(basename $src_dir)
+              recipe={{.TEST_NAME_PREFIX}}
+              testType={{.TEST_TYPE}}
+              testName="Test${module^}${recipe^}${testType^}"
+              testDirResolved="$module/$testType"
+
+
+              cd $testDirResolved
+              go test -v -timeout 30m -parallel 128 -run "^$testName"
+
+              echo "[ ok ] Finished running terratest tests"
+        silent: true
